In [1]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [2]:
arrayA = np.random.randint(1, 10, (3, 3))
arrayB = np.random.randint(1, 10, (3, 3))

print("3x3 Array:")
print(arrayA)
print(arrayB)

3x3 Array:
[[7 4 8]
 [5 7 3]
 [7 8 5]]
[[4 8 8]
 [3 6 5]
 [2 8 6]]


# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [3]:
# Your code here
summ = arrayA + arrayB
print("Tổng từng phần tử:")
print(summ)

Tổng từng phần tử:
[[11 12 16]
 [ 8 13  8]
 [ 9 16 11]]


In [4]:
multi = arrayA * arrayB
print("Tích từng phần tử:")
print(multi)

Tích từng phần tử:
[[28 32 64]
 [15 42 15]
 [14 64 30]]


In [5]:
# matmul = arrayA @ arrayB
matmul = np.dot(arrayA, arrayB)
print("Tích vô hướng:")
print(matmul)

Tích vô hướng:
[[ 56 144 124]
 [ 47 106  93]
 [ 62 144 126]]


# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [6]:
# Your code here
def array_sum(arr):
    return np.sum(arr)

test_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Tổng tất cả các phần tử trong mảng: ", array_sum(test_array))

Tổng tất cả các phần tử trong mảng:  21


In [2]:
import numpy as np 

a = np.array([1, 2])
b = np.array([[1, 3], [1,3]])

# print(a * b)
print(np.dot(a, b))
# print(np.multiply(a, b))

[3 9]
